### PR TITLE
don't modify /usr/bin

### PR DESCRIPTION
**Pull request by meredrica**
the cp should not be needed

### CODE REVIEW

**Comment by meredrica** [comment]
also PLEASE enable the issues tracker.
the script fails at:
make -j2 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- uImage modules\
with:
make[1]: **\* No rule to make target `firmware/ap6210/bcm20710a1.hcd', needed by`__fw_modbuild'.  Stop.

**Comment by Arrheniu2** [comment]
Hi : i think the error comes from a change made by patwood in his kernel branch :+1: 

Patwood "I've uploaded an update to this archive that includes the ap6210 firmware. I've also updated the pat-3.4.75-ct branch on my github repo so it copies these files to lib/firmware in the output directory as part of the make modules_install process."

i have no idea about compiling.. just trying to help.

i builded without problems yesterday (after commit 65 from Igor) and worked fine

**Comment by Arrheniu2** [comment]
about the pull , why dont put fex2bin in /usr/bin i find it useful to change the video output for example, what is the problem of copying this executable to /usr/bin?  just asking :D

**Comment by igorpecovnik** [comment]
Compilation errors fixed. I find necessary to have fex2bin tools, but yes cp to /usr/bin is a bit dirty.

I changed to /usr/local/bin

Tnx

**Comment by meredrica** [comment]
@Arrheniu2 because fex2bin is going to end on the build host, not the cubie truck :)
@igorpecovnik can you enable the issue tracking and then maybe close this pull if you fix it differently?

**Comment by igorpecovnik** [comment]
enabled issue tracking

**Pull request closed without merging**
